version: "2"

services:
  robabby:
    container_name: robabby
    build:
      context: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      # mount empty node_modules exclude the node_modules on host system from mounting into the container
      - node_modules:/home/node/app/node_modules
      # - .cache:/home/node/app/.cache
      - public:/home/node/app/public
    ports:
      - "8000:8000"
    command: "yarn devDocker"
volumes:
  node_modules:
  public:
